version: 2.1
orbs:
  sonar: bulderbank/sonar@1.2.1

jobs:
  code_quality_scan:
    executor: sonar/default
    steps:
      - sonar/scan
            
workflows:
  scan:
    jobs:
      - code_quality_scan

