version: 2.1
orbs:
  sonar: bulderbank/sonar@1.2.1

jobs:
  code_quality_scan:
    executor: sonar/default
    steps:
      - run: |
          mkdir /root/sonar-scanner/conf
          cp ~/project/sonar-scanner.properties /root/sonar-scanner/conf/sonar-scanner.properties
      - sonar/scan
            
workflows:
  scan:
    jobs:
      - code_quality_scan

